FROM node:latest
WORKDIR /app
COPY . .
# Install newman-reporter-csv globally
RUN npm i @tanstack/react-query@4.28.0
RUN npm i @tanstack/react-query-devtools@4.28.0
RUN npm i zustand@4.3.6
RUN npm i @heroicons/react@2.0.16
RUN npm i react-router-dom@6.10.0 axios@1.3.4
RUN npm install -D tailwindcss